name: Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Pytest and Pyspark dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pyspark
    - name: Run Unit Tests
      run: |
        pytest
